# Generated by Django 5.2.3 on 2025-12-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_role_auditlog_budget_notification_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_code',
        ),
    ]
