# Generated by Django 4.2.27 on 2025-12-10 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='beneficiaries',
            field=models.TextField(blank=True, help_text='Names of beneficiaries (comma-separated or list)', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proponent_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
