# Generated by Django 4.2.27 on 2025-12-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_add_proposal_proponent_beneficiaries_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
