# Generated by Django 4.2.27 on 2025-12-11 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_extensionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extension_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extensionrequest',
            name='approved_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionrequest',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extensionrequest',
            name='requested_extension_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extensionrequest',
            name='letter',
            field=models.FileField(blank=True, null=True, upload_to='extension_letters/'),
        ),
    ]
