# Generated by Django 4.2.27 on 2025-12-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_extensionrequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
