# Generated by Django 4.2.27 on 2025-12-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_proposal_latitude_proposal_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('planning', 'Planning'), ('development', 'Development'), ('testing', 'Testing'), ('documentation', 'Documentation'), ('review', 'Review'), ('deployment', 'Deployment'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
    ]
