# Generated by Django 4.2.27 on 2025-12-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_add_personal_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
