# Generated by Django 4.2.27 on 2025-12-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_fix_personal_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltask',
            name='description',
        ),
        migrations.AddField(
            model_name='personaltask',
            name='checklist',
            field=models.JSONField(default=list, help_text="List of checklist items with format: [{'text': 'task description', 'completed': false}, ...]"),
        ),
        migrations.AlterField(
            model_name='personaltask',
            name='project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='personal_tasks', to='myapp.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaltask',
            name='title',
            field=models.CharField(help_text='Project-specific task title', max_length=255),
        ),
    ]
