# Generated by Django 4.2.27 on 2025-12-19 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_update_personal_task_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(help_text='The task that must be completed first', on_delete=django.db.models.deletion.CASCADE, related_name='successor_dependencies', to='myapp.task')),
                ('successor', models.ForeignKey(help_text='The task that depends on the predecessor', on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_dependencies', to='myapp.task')),
            ],
            options={
                'verbose_name': 'Task Dependency',
                'verbose_name_plural': 'Task Dependencies',
                'ordering': ['created_at'],
                'unique_together': {('predecessor', 'successor')},
            },
        ),
    ]
