# Generated by Django 4.2.27 on 2025-12-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_taskdependency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskDependency',
        ),
    ]
