# Generated by Django 4.2.27 on 2025-12-19 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_taskdependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_type', models.CharField(choices=[('user_productivity', 'User Productivity'), ('project_progress', 'Project Progress'), ('task_completion_rates', 'Task Completion Rates'), ('time_tracking_summary', 'Time Tracking Summary')], max_length=50, unique=True)),
                ('data', models.JSONField(help_text='Cached reporting data')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='When this cache expires')),
            ],
            options={
                'verbose_name': 'Reporting Cache',
                'verbose_name_plural': 'Reporting Cache',
            },
        ),
        migrations.CreateModel(
            name='TaskTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_spent', models.DecimalField(decimal_places=2, help_text='Hours spent on this task entry', max_digits=6)),
                ('description', models.TextField(blank=True, help_text='Description of work done', null=True)),
                ('date_worked', models.DateField(default=django.utils.timezone.now, help_text='Date when the work was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='myapp.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Time Entry',
                'verbose_name_plural': 'Task Time Entries',
                'ordering': ['-date_worked', '-created_at'],
                'unique_together': {('task', 'user', 'date_worked', 'created_at')},
            },
        ),
    ]
