# Generated by Django 4.2.27 on 2025-12-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_add_time_tracking_and_reporting'),
    ]

    operations = [
        migrations.RunSQL(
            'DROP TABLE IF EXISTS myapp_tasktimeentry;',
            reverse_sql='CREATE TABLE myapp_tasktimeentry (id INTEGER PRIMARY KEY, user_id INTEGER, task_id INTEGER, hours_spent DECIMAL(5,2), date_worked DATE, notes TEXT, created_at DATETIME, updated_at DATETIME);'
        ),
        migrations.RunSQL(
            'DROP TABLE IF EXISTS myapp_reportingcache;',
            reverse_sql='CREATE TABLE myapp_reportingcache (id INTEGER PRIMARY KEY, cache_type VARCHAR(50), data TEXT, expires_at DATETIME, last_updated DATETIME, created_at DATETIME, updated_at DATETIME);'
        ),
    ]
