# Generated by Django 4.2.27 on 2025-12-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20251220_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='systemhealth',
            name='metric_type',
            field=models.CharField(choices=[('cpu_usage', 'CPU Usage'), ('memory_usage', 'Memory Usage'), ('disk_usage', 'Disk Usage'), ('database_connections', 'Database Connections'), ('active_users', 'Active Users'), ('response_time', 'Response Time'), ('network_latency', 'Network Latency'), ('uptime', 'System Uptime'), ('error_rate', 'Error Rate'), ('queue_length', 'Queue Length')], max_length=50),
        ),
    ]
