# Generated by Django 4.2.27 on 2025-12-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_delete_reportingcache_alter_message_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('task', 'Task'), ('project', 'Project'), ('chat', 'Group Chat'), ('announcement', 'Announcement'), ('budget', 'Budget'), ('proposal', 'Proposal')], default='general', max_length=20),
        ),
    ]
