# Generated by Django 4.2.27 on 2025-12-31 02:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_delete_reportingcache_notification_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.PositiveIntegerField()),
                ('delivered_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='allocated', max_length=20)),
                ('allocation_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_allocations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('pieces', 'Pieces'), ('sets', 'Sets'), ('units', 'Units'), ('kg', 'Kilograms'), ('liters', 'Liters'), ('meters', 'Meters'), ('boxes', 'Boxes'), ('packs', 'Packs')], default='pieces', max_length=20)),
                ('estimated_unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost per unit for reference', max_digits=12, null=True)),
                ('specifications', models.TextField(blank=True, help_text='Technical specifications, model numbers, etc.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.equipmentcategory')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProjectEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.PositiveIntegerField()),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('installed', 'Installed'), ('operational', 'Operational'), ('returned', 'Returned'), ('damaged', 'Damaged')], default='delivered', max_length=20)),
                ('serial_numbers', models.TextField(blank=True, help_text='Serial numbers, batch numbers, etc.', null=True)),
                ('condition_notes', models.TextField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('budget_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='myapp.budgetallocation')),
                ('delivered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_deliveries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_deliveries', to='myapp.project')),
            ],
            options={
                'verbose_name_plural': 'Project Equipment',
            },
        ),
        migrations.AlterField(
            model_name='budget',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='myapp.budget'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='equipment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='myapp.equipmentitem'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetallocation',
            unique_together={('budget', 'equipment_item')},
        ),
    ]
