# Generated by Django 4.2.27 on 2025-12-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_budgetallocation_equipmentcategory_equipmentitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='total_allocated_items',
            field=models.PositiveIntegerField(default=0, help_text='Total number of equipment items allocated to this budget'),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_delivered_items',
            field=models.PositiveIntegerField(default=0, help_text='Total number of equipment items delivered from this budget'),
        ),
    ]
