# Generated by Django 4.2.27 on 2025-12-31 03:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_convert_budget_to_equipment_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_number', models.CharField(choices=[('tranche_1', 'Tranche 1'), ('tranche_2', 'Tranche 2'), ('tranche_3', 'Tranche 3')], max_length=20)),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Amount allocated for this tranche', max_digits=15)),
                ('released_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually released', max_digits=15)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('check_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ada_number', models.CharField(blank=True, help_text='ADA (Authority to Debit Account) number', max_length=100, null=True)),
                ('liquidation_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('audited', 'Audited')], default='not_started', max_length=20)),
                ('liquidation_date', models.DateField(blank=True, null=True)),
                ('amount_liquidated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('utilization_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of funds utilized', max_digits=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tranches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'tranche_number'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='justification',
            field=models.TextField(blank=True, help_text='Required justification for critical actions (budget updates, project status changes)', null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='counterpart_contribution',
            field=models.TextField(blank=True, help_text="Proponent's counterpart contribution (building space, in-kind services, etc.)", null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='counterpart_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monetary value of counterpart contribution', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='delivered_equipment_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monetary value of equipment delivered', max_digits=18),
        ),
        migrations.AddField(
            model_name='budget',
            name='lib_category',
            field=models.CharField(choices=[('PS', 'Personal Services (Salaries/Honoraria)'), ('MOOE', 'Maintenance & Other Operating Expenses'), ('EO_CO', 'Equipment/Capital Outlay')], default='PS', help_text='DOST Line-Item Budget Category', max_length=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_equipment_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total monetary value of equipment allocated', max_digits=18),
        ),
        migrations.AddField(
            model_name='project',
            name='ownership_end_date',
            field=models.DateField(blank=True, help_text='Date when full ownership is achieved (3 years after start)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ownership_start_date',
            field=models.DateField(blank=True, help_text='Date when equipment ownership begins', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tna_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('equipment_selected', 'Equipment Selected'), ('delivery_pending', 'Delivery Pending')], default='not_started', help_text='Technological Need Assessment status', max_length=20),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='property_tag_number',
            field=models.CharField(blank=True, help_text='DOST property tag number for inventory tracking', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='fund_source',
            field=models.CharField(choices=[('DOST_GIA', 'DOST-GIA (Grants-in-Aid)'), ('SETUP', 'SETUP (Small Enterprise Technology Upgrading Program)'), ('LOCAL_REGIONAL', 'Local/Regional Funds'), ('OTHER', 'Other')], default='DOST_GIA', max_length=50),
        ),
        migrations.AddField(
            model_name='projecttranche',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='myapp.project'),
        ),
        migrations.AlterUniqueTogether(
            name='projecttranche',
            unique_together={('project', 'tranche_number')},
        ),
    ]
