# Generated by Django 4.2.27 on 2025-12-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_add_budget_lib_fields_and_tranche'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranche',
            name='justification',
            field=models.TextField(default='Tranche allocation for project implementation', help_text='Justification for this tranche allocation'),
        ),
    ]
