# Generated by Django 4.2.27 on 2026-01-03 11:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_add_tranche_justification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrancheRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranche_number', models.PositiveIntegerField(choices=[(1, '1st Tranche'), (2, '2nd Tranche'), (3, '3rd Tranche'), (4, '4th Tranche'), (5, '5th Tranche')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('check_number', models.CharField(blank=True, help_text='Check/ADA number for the release', max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('liquidation_status', models.CharField(choices=[('pending', 'Pending Liquidation'), ('partial', 'Partially Liquidated'), ('submitted', 'Liquidation Submitted'), ('under_review', 'Under Review'), ('approved', 'Liquidation Approved'), ('rejected', 'Liquidation Rejected')], default='pending', max_length=20)),
                ('liquidation_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount liquidated so far', max_digits=18)),
                ('liquidation_date', models.DateField(blank=True, null=True)),
                ('liquidation_document', models.FileField(blank=True, null=True, upload_to='liquidation_documents/')),
                ('is_released', models.BooleanField(default=False)),
                ('eligible_for_next_tranche', models.BooleanField(default=False, help_text='Automatically set when liquidation is approved')),
                ('required_liquidation_percentage', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Required percentage of liquidation before next tranche', max_digits=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tranche Release',
                'verbose_name_plural': 'Tranche Releases',
                'ordering': ['project', 'tranche_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ownership_end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ownership_start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tna_status',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='reason',
            field=models.TextField(blank=True, help_text='Justification or reason for this action (required for sensitive operations)', null=True),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='lease_start_date',
            field=models.DateField(blank=True, help_text='Start date of 3-year SETUP equipment lease period', null=True),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='ownership_status',
            field=models.CharField(choices=[('dost_owned', 'DOST-Owned (Under Lease)'), ('transfer_pending', 'Transfer Pending'), ('beneficiary_owned', 'Beneficiary-Owned')], default='dost_owned', help_text='Equipment ownership status for SETUP projects', max_length=20),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='ownership_transfer_date',
            field=models.DateField(blank=True, help_text='Date when ownership was transferred to beneficiary', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tna_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tna_notes',
            field=models.TextField(blank=True, help_text='Notes from TNA assessment', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tna_status',
            field=models.CharField(choices=[('not_started', 'TNA Not Started'), ('in_progress', 'TNA In Progress'), ('completed', 'TNA Completed'), ('equipment_selection', 'Equipment Selection'), ('procurement', 'Under Procurement'), ('delivery_pending', 'Delivery Pending'), ('delivered', 'Equipment Delivered'), ('operational', 'Operational')], default='not_started', help_text='Technology Needs Assessment status for beneficiaries', max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('status_change', 'Status Change'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('transfer', 'Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectequipment',
            name='property_tag_number',
            field=models.CharField(blank=True, help_text='DOST Property Tag Number for inventory audits (e.g., DOST-R10-2024-001)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trancherelease',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tranche_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trancherelease',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranche_releases', to='myapp.project'),
        ),
        migrations.AlterUniqueTogether(
            name='trancherelease',
            unique_together={('project', 'tranche_number')},
        ),
    ]
