# Generated by Django 4.2.27 on 2026-01-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_calendarevent_digitalsignature_mention_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportingCache',
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('pending_procurement', 'Pending Procurement'), ('available', 'Available for Allocation'), ('partially_allocated', 'Partially Allocated'), ('fully_allocated', 'Fully Allocated'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending_procurement', max_length=25),
        ),
        migrations.DeleteModel(
            name='TaskTimeEntry',
        ),
    ]
